{
    "repo": "logging-log4j-audit",
    "bugs": [
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AttributeConverter_65",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/AttributeConverter.java",
                "line": 65,
                "deref_field": "getConstraints()",
                "npe_class": "AttributeConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 48.928488597040996
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "InterfacesGenerator_169",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/generator/InterfacesGenerator.java",
                "line": 170,
                "deref_field": "eventAttributes",
                "npe_class": "InterfacesGenerator",
                "npe_method": "generateSource",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 49.76330897491425
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.generator.TestInterfacesGenerator",
                        "method": "testInterfaceGenerator",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.generator.TestInterfacesGenerator.testInterfaceGenerator(TestInterfacesGenerator.java:55)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AttributeConverter_73",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/AttributeConverter.java",
                "line": 74,
                "deref_field": "getId()",
                "npe_class": "AttributeConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 53.25857715192251
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "InterfacesGenerator_268",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/generator/InterfacesGenerator.java",
                "line": 269,
                "deref_field": "getAttributes()",
                "npe_class": "InterfacesGenerator",
                "npe_method": "generateSource",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 52.98551758984104
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.generator.TestInterfacesGenerator",
                        "method": "testInterfaceGenerator",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.generator.TestInterfacesGenerator.testInterfaceGenerator(TestInterfacesGenerator.java:55)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "EventConverter_70",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/EventConverter.java",
                "line": 70,
                "deref_field": "getAttributes()",
                "npe_class": "EventConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 47.532400246942416
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_395",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 396,
                "deref_field": "value",
                "npe_class": "LogEventFactory",
                "npe_method": "validateContextConstraint",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 47.11884779203683
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: Expected exception: org.apache.logging.log4j.audit.exception.ConstraintValidationException\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: Should have thrown a ConstraintValidationException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:91)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: Expected exception: org.apache.logging.log4j.audit.exception.ConstraintValidationException\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: Should have thrown a ConstraintValidationException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:91)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "CatalogManagerImpl_172",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/catalog/CatalogManagerImpl.java",
                "line": 173,
                "deref_field": "attribute",
                "npe_class": "CatalogManagerImpl",
                "npe_method": "addEntry",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 57.24545762385242
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.catalog.CatalogManagerTest",
                        "method": "testCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.catalog.CatalogManagerTest.testCatalog(CatalogManagerTest.java:31)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.catalog.CatalogManagerTest.testCatalog(CatalogManagerTest.java:31)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "CatalogManagerImpl_140",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/catalog/CatalogManagerImpl.java",
                "line": 141,
                "deref_field": "getAttributes()",
                "npe_class": "CatalogManagerImpl",
                "npe_method": "initializeData",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 45.82644877396524
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "ConstraintModel_80",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/model/ConstraintModel.java",
                "line": 81,
                "deref_field": "getConstraints()",
                "npe_class": "ConstraintModel",
                "npe_method": "setAttribute",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 38.82993393507786
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "EventConverter_74",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/EventConverter.java",
                "line": 75,
                "deref_field": "eventAttributeModel",
                "npe_class": "EventConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 38.6134525348898
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AbstractEventLogger_113",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/AbstractEventLogger.java",
                "line": 113,
                "deref_field": "getAttributes()",
                "npe_class": "AbstractEventLogger",
                "npe_method": "logEvent",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 37.75803237315267
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:145)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "InterfacesGenerator_172",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/generator/InterfacesGenerator.java",
                "line": 177,
                "deref_field": "attribute",
                "npe_class": "InterfacesGenerator",
                "npe_method": "generateSource",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 47.547484126873314
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.generator.TestInterfacesGenerator",
                        "method": "testInterfaceGenerator",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.generator.TestInterfacesGenerator.testInterfaceGenerator(TestInterfacesGenerator.java:55)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "CatalogManagerImpl_90",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/catalog/CatalogManagerImpl.java",
                "line": 90,
                "deref_field": "getAttributes()",
                "npe_class": "CatalogManagerImpl",
                "npe_method": "getAttributes",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 43.08898838120513
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:145)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AuditCatalogManager_94",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-war/src/main/java/org/apache/logging/log4j/audit/service/catalog/AuditCatalogManager.java",
                "line": 97,
                "deref_field": "catalogModel",
                "npe_class": "AuditCatalogManager",
                "npe_method": "initialize",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 41.84105830290355
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "EventConverter_55",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/EventConverter.java",
                "line": 56,
                "deref_field": "getId()",
                "npe_class": "EventConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 41.668555366806686
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: java.lang.IllegalArgumentException: The given id must not be null!\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AttributeConverter_48",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/AttributeConverter.java",
                "line": 49,
                "deref_field": "getId()",
                "npe_class": "AttributeConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 23.978950273012742
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: The given id must not be null!\nCaused by: java.lang.IllegalArgumentException: The given id must not be null!\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_107",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 107,
                "deref_field": "maxLength",
                "npe_class": "LogEventFactory",
                "npe_method": "getMaxLength",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 28.728211388923228
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClassToString",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClassToString(LogoutTest.java:30)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClassToString(LogoutTest.java:30)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClassToString(LogoutTest.java:30)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClassToString",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:39)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:39)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:39)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClassToString",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_389",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 394,
                "deref_field": "constraint",
                "npe_class": "LogEventFactory",
                "npe_method": "validateContextConstraint",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 24.804003837052733
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Error logging event Logout\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Error logging event Logout\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_378",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 379,
                "deref_field": "reqCtxConstraints",
                "npe_class": "LogEventFactory",
                "npe_method": "validateContextConstraints",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 20.30599993490614
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Error logging event Logout\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditClass",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Error logging event Logout\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditClass(LogoutTest.java:41)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "Event_178",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-api/src/main/java/org/apache/logging/log4j/catalog/api/Event.java",
                "line": 180,
                "deref_field": "attributes",
                "npe_class": "Event",
                "npe_method": "toString",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 24.028781512053683
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.catalog.CatalogManagerTest",
                        "method": "testCatalog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.catalog.CatalogManagerTest.testCatalog(CatalogManagerTest.java:40)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_102",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 102,
                "deref_field": "eventName",
                "npe_class": "LogEventFactory",
                "npe_method": "getEventName",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 20.50958530907519
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testDefaultExceptionHandlerIsInvokedOnEventLogFailure",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLog(TransferTest.java:260)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForInvalidRequestContextAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingRequestContextAttribute(TransferTest.java:79)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingRequestContextAttribute(TransferTest.java:224)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testCustomExceptionHandlerIsPassedToEvent(TransferTest.java:204)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditClass",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForInvalidRequestContextAttribute(TransferTest.java:65)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingEventAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testValidationFailureForMissingEventAttribute(TransferTest.java:102)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLogWithMissingRequestContextAttribute",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditClass(TransferTest.java:120)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testValidationFailureForMissingEventAttribute",
                        "exn_type": "java.lang.AssertionError",
                        "stack_trace": "java.lang.AssertionError: \n\nExpected: (an instance of org.apache.logging.log4j.audit.exception.AuditException and exception with cause is an instance of org.apache.logging.log4j.LoggingException and exception with message a string containing \"Error logging event transfer\")\n     but: an instance of org.apache.logging.log4j.audit.exception.AuditException <java.lang.NullPointerException> is a java.lang.NullPointerException\nStacktrace was: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEventName(LogEventFactory.java:103)\n\tat org.apache.logging.log4j.audit.LogEventFactory.buildAuditMessage(LogEventFactory.java:112)\n\tat org.apache.logging.log4j.audit.LogEventFactory.getEvent(LogEventFactory.java:93)\n\tat org.apache.logging.log4j.audit.TransferTest.setUpMinimumEvent(TransferTest.java:171)\n\tat org.apache.logging.log4j.audit.TransferTest.testDefaultExceptionHandlerIsInvokedOnEventLogFailure(TransferTest.java:186)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\n\tat org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n\tat org.junit.rules.RunRules.evaluate(RunRules.java:20)\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\n\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testCustomExceptionHandlerIsPassedToEvent",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.TransferTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<java.lang.NullPointerException>\n\tat org.apache.logging.log4j.audit.TransferTest.testAuditLogWithMissingEventAttribute(TransferTest.java:239)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "LogEventFactory_137",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/LogEventFactory.java",
                "line": 138,
                "deref_field": "properties",
                "npe_class": "LogEventFactory",
                "npe_method": "logEvent",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 25.54645938007161
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.LogoutTest",
                        "method": "testAuditLog",
                        "exn_type": "java.lang.NullPointerException",
                        "stack_trace": "java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.LogoutTest.testAuditLog(LogoutTest.java:67)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "CatalogManagerImpl_168",
            "npe_info": {
                "filepath": "log4j-audit/log4j-audit-api/src/main/java/org/apache/logging/log4j/audit/catalog/CatalogManagerImpl.java",
                "line": 169,
                "deref_field": "getAttributes()",
                "npe_class": "CatalogManagerImpl",
                "npe_method": "addEntry",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 29.508995323907584
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLogger",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLogger(AuditLoggerTest.java:85)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingRequestContextAttribute",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingEventAttribute(AuditLoggerTest.java:127)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testMissingEventAttribute",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testAuditLoggerWithBasicCatalog(AuditLoggerTest.java:143)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.AuditLoggerTest",
                        "method": "testAuditLoggerWithBasicCatalog",
                        "exn_type": "java.lang.Exception",
                        "stack_trace": "java.lang.Exception: Unexpected exception, expected<org.apache.logging.log4j.audit.exception.ConstraintValidationException> but was<org.apache.logging.log4j.audit.exception.AuditException>\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.buildAuditLogger(AuditLoggerTest.java:71)\n\tat org.apache.logging.log4j.audit.AuditLoggerTest.testMissingRequestContextAttribute(AuditLoggerTest.java:116)\n"
                    },
                    {
                        "classname": "org.apache.logging.log4j.audit.catalog.CatalogManagerTest",
                        "method": "testCatalog",
                        "exn_type": "org.apache.logging.log4j.audit.exception.AuditException",
                        "stack_trace": "org.apache.logging.log4j.audit.exception.AuditException: Unable to initialize catalog data\n\tat org.apache.logging.log4j.audit.catalog.CatalogManagerTest.testCatalog(CatalogManagerTest.java:31)\nCaused by: java.lang.NullPointerException\n\tat org.apache.logging.log4j.audit.catalog.CatalogManagerTest.testCatalog(CatalogManagerTest.java:31)\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        },
        {
            "repo": "logging-log4j-audit",
            "bug_id": "AttributeConverter_69",
            "npe_info": {
                "filepath": "log4j-catalog/log4j-catalog-jpa/src/main/java/org/apache/logging/log4j/catalog/jpa/converter/AttributeConverter.java",
                "line": 70,
                "deref_field": "getConstraints()",
                "npe_class": "AttributeConverter",
                "npe_method": "convert",
                "sink_field": null,
                "jvmti_identify_succeed": null,
                "is_original": null
            },
            "build_info": {
                "compiled": true,
                "build_command": "mvn test-compile -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "java_version": 8,
                "error_message": null,
                "time": 21.043320594122633
            },
            "test_info": {
                "test_command": "mvn test -V -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dcobertura.skip=true -Drat.skip=true -Dlicense.skip=true -Dfindbugs.skip=true -Dgpg.skip=true -Dskip.npm=true -Dskip.gulp=true -Dskip.bower=true",
                "fail_buggy": true,
                "pass_fixed": true,
                "testcases": [
                    {
                        "classname": "org.apache.logging.log4j.audit.service.CatalogTest",
                        "method": "testCatalogAPI",
                        "exn_type": "java.lang.IllegalStateException",
                        "stack_trace": "java.lang.IllegalStateException: Failed to load ApplicationContext\nCaused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditController': Unsatisfied dependency expressed through field 'auditLogger'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogger' defined in org.apache.logging.log4j.audit.service.config.WebMvcAppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.logging.log4j.audit.AuditLogger]: Factory method 'auditLogger' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditManager': Invocation of init method failed; nested exception is java.lang.NullPointerException\nCaused by: java.lang.NullPointerException\n"
                    }
                ]
            },
            "patches": [],
            "time_to_generate_patches": 0
        }
    ],
    "repository_info": null
}